dist: xenial
language: python
notifications:
  email: false
python:
  - 3.8
  - 3.7
  - 3.6
compiler:
  - clang
  - gcc
stages:
  - lint
  - test


.lint: &lint
  git:
    submodules: false
  python: 3.6
  env:
    - MINREQ=0
  stage: lint
  script: make lint

jobs:
  include:
    - *moban
    - *lint

stage: test
before_install:
  - sudo pip install pytest
  - sudo apt-get update
  - sudo apt-get install -y gcc-multilib
  - sudo apt-get install -y zlib1g-dev
  - sudo apt-get install -y zlib1g-dev:i386
  - sudo apt-get install -y gcc
  - sudo apt-get install -y valgrind
  - pip install -r tests/requirements.txt
  - git clone https://github.com/jmcnamara/libxlsxwriter.git
  - cd libxlsxwriter
  - make
  - sudo make install
  - cd ../
  - rm libxlsxwriter/ -rf
  - if [[ -f min_requirements.txt && "$MINREQ" -eq 1 ]]; then
      mv min_requirements.txt requirements.txt ;
    fi
  - test ! -f rnd_requirements.txt ||
    pip install --no-deps -r rnd_requirements.txt
  - test ! -f rnd_requirements.txt || pip install -r rnd_requirements.txt ;
  - pip install -r tests/requirements.txt
script:
  - make test
after_success:
  codecov
